sudo: required 
services:
  - docker 

before_install:
  - docker build -t khalil/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true khalil/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: docker-travis
  env: "dockertravis-env"
  bucket_name: "elasticbeanstalk-eu-west-3-907076315131Info"
  bucket_path: "docker-travis"
  on:
    branch: master    
  access_key_id: $AWS_KEY_ID
  secret_access_key:
    secure:  "$AWS_SECRET_KEY"
